import { Geist, Geist_Mono } from "next/font/google";
import ReduxProvider from "@/redux/provider";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vikram Sarabhai School Bardoli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main className="flex-1">
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>
      </body>
    </html>
  );
}
